services:
  - type: web
    name: omio-studio
    runtime: node
    plan: free
    buildCommand: npm install --no-cache
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ADMIN_EMAIL
        value: admin@omio.studio
      - key: ADMIN_PASS
        sync: false
      - key: COMPANY_LEADER_EMAIL
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: MAIL_FROM
        sync: false
